server.port=8081

spring.profiles.default=szururu1

spring.application.name=BOBECZEK

server.jetty.threads.max=20
server.jetty.threads.min=10
server.jetty.threads.max-queue-capacity=1

spring.mvc.async.request-timeout=30000

server.connection-timeout=-1